name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ZUSHH_SHH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.ZUSHH_HOST }} << 'EOF'
            set -e

            cd ~/nazam-core

            echo "ðŸ‘‰ Cleaning npm cache & PM2 logs"
            npm cache clean --force
            pm2 flush

            echo "ðŸ‘‰ Pulling latest code"
            git pull origin main

            echo "ðŸ‘‰ Installing production dependencies"
            rm -rf node_modules
            npm install --omit=dev

            echo "ðŸ‘‰ Restarting core service"
            pm2 restart zushh-core || pm2 start npm --name "zushh-core" -- run start
            pm2 save
          EOF
